### ISSUE TITLE
iOS包含UIWebView导致上架苹果应用商店提交失败

### ISSUE THREAD

**Issue by ZhangTaoK** [jpush/jverification-react-native#19]
Binary file ./node_modules/jverification-react-native/ios/RCTJVerificationModule/TYRZSDK.framework/TYRZSDK matches

**Comment by xiaoyongchen** [comment]
> Binary file ./node_modules/jverification-react-native/ios/RCTJVerificationModule/TYRZSDK.framework/TYRZSDK matches

你好如何解决的，是不用了吗

**Comment by hyhSuper** [comment]
更新移动sdk修复了该问题。

**Comment by ILoveChy** [comment]
> 更新移动sdk修3复了该问题。

eeeee
