### ISSUE TITLE
iOS工程链接报错

### ISSUE THREAD

**Issue by stelalae** [jpush/jverification-react-native#2]
![image](https://user-images.githubusercontent.com/5012217/58525137-26d96080-81fd-11e9-8814-c2c247d4ac75.png)

**Comment by LiangQiangQiang** [comment]
你好 解决了吗    我也遇到了

**Comment by stelalae** [comment]
没有。我最后改为自己原生暴露方法出来

**Comment by wicked-tc130** [comment]
已更新版本
