### ISSUE TITLE
customView 自定义控件默认灰色背景问题

### ISSUE THREAD

**Issue by mushroot** [jpush/jverification-react-native#25]
自定义控件，默认有一个黑色背景，请问该如何去除。
![IMG_3C68715CC1DB-1](https://user-images.githubusercontent.com/3608366/109838878-86418b80-7c81-11eb-9a5c-c0fcd8622370.jpeg)

**Comment by songxiaoliang** [comment]
@mushroot 解决了吗

**Comment by mushroot** [comment]
是组件的背景无法设置为透明，当时的解决方案是有做了一张和灰色部分一样大小的图片作为模块的背景。
